# Generated by Django 5.2.8 on 2025-12-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='currency',
            field=models.CharField(choices=[('USD', 'USA ($)'), ('INR', 'India (₹)'), ('GBP', 'UK (£)'), ('EUR', 'Europe (€)'), ('JPY', 'Japan (¥)')], default='USD', max_length=3),
        ),
    ]
