# Generated by Django 5.2.8 on 2025-12-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Your starting balance when you began using the app', max_digits=15),
        ),
    ]
