# Generated by Django 5.2.8 on 2025-12-22 18:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('Emergency Fund', 'Emergency Fund'), ('Travel', 'Travel'), ('Education', 'Education'), ('Home', 'Home'), ('Vehicle', 'Vehicle'), ('Gadgets', 'Gadgets'), ('Other', 'Other')], default='Other', max_length=50)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
