# Generated by Django 5.2.8 on 2025-12-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_badge_challenge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
